<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Action rule</name>
  <uuid>731996b0-aa19-4997-9483-ae57577d0c49</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if Name is defined

then set decision to "Hello " + Name + "!" + 'Weather Advice';]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
